const GET_STORIES = 'GET_STORIES';
const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
const GET_STORIES_FAILURE = 'GET_STORIES_FAILURE';
const UPDATE_STORIES = 'UPDATE_STORIES';
const UPDATE_STORIES_SUCCESS = 'UPDATE_STORIES_SUCCESS';
const UPDATE_STORIES_FAILURE = 'UPDATE_STORIES_FAILURE';
const CREATE_STORIES = 'CREATE_STORIES';
const CREATE_STORIES_SUCCESS = 'CREATE_STORIES_SUCCESS';
const CREATE_STORIES_FAILURE = 'CREATE_STORIES_FAILURE';
const DELETE_STORIES = 'DELETE_STORIES';
const DELETE_STORIES_SUCCESS = 'DELETE_STORIES_SUCCESS';
const DELETE_STORIES_FAILURE = 'DELETE_STORIES_FAILURE';

export {
  GET_STORIES,
  GET_STORIES_SUCCESS,
  GET_STORIES_FAILURE,
  UPDATE_STORIES,
  UPDATE_STORIES_SUCCESS,
  UPDATE_STORIES_FAILURE,
  CREATE_STORIES,
  CREATE_STORIES_SUCCESS,
  CREATE_STORIES_FAILURE,
  DELETE_STORIES,
  DELETE_STORIES_SUCCESS,
  DELETE_STORIES_FAILURE
}