const GET_STORIES = 'GET_STORIES';
const GET_STORIES_SUCCESS = 'GET_STORIES_SUCCESS';
const GET_STORIES_FAILURE = 'GET_STORIES_FAILURE';
const EDIT_STORY = 'EDIT_STORY';
const UPDATE_STORY = 'UPDATE_STORY';
const UPDATE_STORY_SUCCESS = 'UPDATE_STORY_SUCCESS';
const UPDATE_STORY_FAILURE = 'UPDATE_STORY_FAILURE';
const CREATE_STORY = 'CREATE_STORY';
const CREATE_STORY_SUCCESS = 'CREATE_STORY_SUCCESS';
const CREATE_STORY_FAILURE = 'CREATE_STORY_FAILURE';
const DELETE_STORY = 'DELETE_STORY';
const DELETE_STORY_SUCCESS = 'DELETE_STORY_SUCCESS';
const DELETE_STORY_FAILURE = 'DELETE_STORY_FAILURE';

export {
  GET_STORIES,
  GET_STORIES_SUCCESS,
  GET_STORIES_FAILURE,
  EDIT_STORY,
  UPDATE_STORY,
  UPDATE_STORY_SUCCESS,
  UPDATE_STORY_FAILURE,
  CREATE_STORY,
  CREATE_STORY_SUCCESS,
  CREATE_STORY_FAILURE,
  DELETE_STORY,
  DELETE_STORY_SUCCESS,
  DELETE_STORY_FAILURE
}